name: quran2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  mini_music_visualizer: ^1.1.4
  video_player: ^2.9.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/video/Elahzab/
    - assets/video/Elankaboot/
    - assets/video/Eldukhan/
    - assets/video/Eljathiya/
    - assets/video/Elroom/
    - assets/video/Elsaffat/
    - assets/video/Elsajda/
    - assets/video/Elshoora/
    - assets/video/Elzomar/
    - assets/video/Elzukhruf/
    - assets/video/Fater/
    - assets/video/Fussilat/
    - assets/video/Ghafir/
    - assets/video/Loqman/
    - assets/video/Saba/
    - assets/video/Sad/
    - assets/video/Yaseen/
    


flutter_icons:
  ios: true
  android: false
  image_path: "assets/icons/logoapp.png"